export enum UiILocators {
  SIGN_IN_FORM_PASSWORD_ICON = 'sign-in-form-password-icon',
  SIGN_IN_FORM_SIGN_UP_LINK = 'sign-in-form-sign-up-link',
  SIGN_IN_FORM_FORGOT_LINK = 'sign-in-form-forgot-link',
  SIGN_IN_FORM_PASSWORD = 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT = 'sign-in-form-submit',
  SIGN_IN_FORM_EMAIL = 'sign-in-form-email',

  SIGN_UP_FORM_CONFIRM_PASSWORD_ICON = 'sign-up-form-confirm-password-icon',
  SIGN_UP_FORM_CONFIRM_PASSWORD = 'sign-up-form-confirm-password',
  SIGN_UP_FORM_PASSWORD_ICON = 'sign-up-form-password-icon',
  SIGN_UP_FORM_FIRST_NAME = 'sign-up-form-first-name',
  SIGN_UP_FORM_BACK_LINK = 'sign-up-form-back-link',
  SIGN_UP_FORM_NICK_NAME = 'sign-up-form-nick-name',
  SIGN_UP_FORM_LAST_NAME = 'sign-up-form-last-name',
  SIGN_UP_FORM_PASSWORD = 'sign-up-form-password',
  SIGN_UP_FORM_SUBMIT = 'sign-up-form-submit',
  SIGN_UP_FORM_EMAIL = 'sign-up-form-email',

  NEW_PASSWORD_FORM_CONFIRM_PASSWORD_ICON = 'new-password-form-confirm-password-icon',
  NEW_PASSWORD_FORM_NEW_PASSWORD_ICON = 'new-password-form-new-password-icon',
  NEW_PASSWORD_FORM_CONFIRM_PASSWORD = 'new-password-form-confirm-password',
  NEW_PASSWORD_FORM_NEW_PASSWORD = 'new-password-form-new-password',
  NEW_PASSWORD_FORM_SUBMIT = 'new-password-form-submit',

  FORGOT_PASSWORD_FORM_BACK_LINK = 'forgot-password-form-back-link',
  FORGOT_PASSWORD_FORM_SUBMIT = 'forgot-password-form-submit',
  FORGOT_PASSWORD_FORM_EMAIL = 'forgot-password-form-email',

  BACK_TO_HOME_BUTTON = 'back-to-home-button',
  BUTTON_UP = 'button-up',

  USER_LAYOUT_SIDEBAR_FLEA_MARKET_LINK = 'user-layout-sidebar-flea-market-link',
  USER_LAYOUT_SIDEBAR_COMMUNITIES_LINK = 'user-layout-sidebar-communities-link',
  USER_LAYOUT_SIDEBAR_MY_GARAGE_LINK = 'user-layout-sidebar-garage-link',
  USER_LAYOUT_SIDEBAR_LOG_BOOKS_LINK = 'user-layout-sidebar-log-books-link',
  USER_LAYOUT_SIDEBAR_SHOPS_LINK = 'user-layout-sidebar-shops-link',
  USER_LAYOUT_SIDEBAR_FEED_LINK = 'user-layout-sidebar-feed-link',
  USER_LAYOUT_SIDEBAR_CARS_LINK = 'user-layout-sidebar-cars-link',
}
